### ISSUE TITLE
jQuery 1.9.1 and Jasmine 1.3.1.2 seem incompatible

### ISSUE THREAD

**Issue by alex-dow** [searls/jasmine-maven-plugin#180]
I am also using requirejs and the out of box requirejs runner.

```
define([], function() {
    describe("WORK DAMN IT", function() {
        it("SHOULD JUST WORK", function() {
        setFixtures('<div id="foobar">hello moto</div>');
        expect($('#foobar').html()).toBe('hello moto');
        });
    });
});
```

This test does not work with jQuery 1.9.1 and does work with jQuery 1.8.3. Using 1.9.1, $('#foobar').html() is undefined. We are NOT using minified/compressed versions of jQuery nor requirejs.

Playing around with <browserVersion></browserVersion> did nothing.

Adding HtmlUnit 2.10 simply didn't work with Jasmine:

[ERROR] Failed to execute goal com.github.searls:jasmine-maven-plugin:1.3.1.2:test (default) on project otif-sample-app: Execution default of goal com.github.searls:jasmine-maven-plugin:1.3.1.2:test failed: An API incompatibility was encountered while executing com.github.searls:jasmine-maven-plugin:1.3.1.2:test: java.lang.NoSuchMethodError: com.gargoylesoftware.htmlunit.WebClient.getOptions()Lcom/gargoylesoftware/htmlunit/WebClientOptions;

Relevant output:

[INFO] Executing Jasmine Specs
May 23, 2013 4:22:58 PM com.gargoylesoftware.htmlunit.javascript.StrictErrorReporter runtimeError
SEVERE: runtimeError: message=[An invalid or illegal selector was specified (selector: '_,:x' error: Invalid selector: *:x).] sourceName=[http://localhost:49895/src/main/site/javascript/lib/jquery-1.9.1.js] line=[4224] lineSource=[null] lineOffset=[0]
May 23, 2013 4:22:59 PM com.gargoylesoftware.htmlunit.DefaultCssErrorHandler error
WARNING: CSS error: 'http://localhost:49895/' [12:52] Error in style rule. (Invalid token "_". Was expecting one of: <EOF>, <S>, <IDENT>, "}", ";".)
May 23, 2013 4:22:59 PM com.gargoylesoftware.htmlunit.DefaultCssErrorHandler warning
WARNING: CSS warning: 'http://localhost:49895/' [12:52] Ignoring the following declarations in this rule.
May 23, 2013 4:23:00 PM com.gargoylesoftware.htmlunit.xml.XmlPage <init>
WARNING: Failed parsing XML document http://localhost:49895/: Content is not allowed in prolog.
May 23, 2013 4:23:00 PM com.gargoylesoftware.htmlunit.xml.XmlPage <init>
WARNING: Failed parsing XML document http://localhost:49895/: Content is not allowed in prolog.
May 23, 2013 4:23:00 PM com.gargoylesoftware.htmlunit.xml.XmlPage <init>
WARNING: Failed parsing XML document http://localhost:49895/: Content is not allowed in prolog.
May 23, 2013 4:23:00 PM com.gargoylesoftware.htmlunit.xml.XmlPage <init>
WARNING: Failed parsing XML document http://localhost:49895/: Content is not allowed in prolog.
[INFO]

Jasmine config:

```
        <plugin>
            <groupId>com.github.searls</groupId>
            <artifactId>jasmine-maven-plugin</artifactId>
            <version>1.3.1.2</version>
            <extensions>true</extensions>
            <executions>
                <execution>
                    <goals>
                        <goal>test</goal>
                    </goals>
                </execution>
            </executions>
            <configuration>
                <baseUrl>src/main/javascript</baseUrl>
                <customRunnerConfiguration>
                                        ${basedir}/src/test/resources/requirejs_config
                </customRunnerConfiguration>
                <specRunnerTemplate>REQUIRE_JS</specRunnerTemplate>
                <preloadSources>
                    <source>${basedir}/src/main/site/javascript/lib/require-2.1.5.js</source>
                    <source>${basedir}/src/main/site/javascript/lib/jquery-1.9.1.js</source>
                    <source>${basedir}/src/main/site/javascript/lib/underscore-1.4.4.js</source>
                    <source>${basedir}/src/main/site/javascript/lib/backbone-1.0.0.js</source>
                    <source>${basedir}/src/main/site/javascript/lib/sinon-1.7.1.js</source>
                    <source>${basedir}/src/main/site/javascript/lib/jasmine-jquery-1.4.2.js</source>
                    <!-- Fill this with libraries that need to be loaded first -->
                </preloadSources>
                <!-- configuration properties will go here -->
            </configuration>
        </plugin>
```
