### ISSUE TITLE
htmlunit fails on querySelector

### ISSUE THREAD

**Issue by robustican** [searls/jasmine-maven-plugin#150]
The error we're seeing is 

TypeError: Cannot find function querySelector in object [object HTMLDocument]

I've tried specifying htmlunit version 2.10 (as is specified at https://github.com/searls/jasmine-maven-plugin/issues/135) and using FIREFOX_3_6 as the browser version but we don't seem to be able to make it work.

I'm hoping that this stuff just works in the 1.3.1 release as htmlunit claims to support querySelector and querySelectorAll
